// components/Base.js
import BasicLayout from '../components/page-layouts/BasicLayout'
import PageSection from '../components/PageSection'

function UGCTerms() {
  return (
    <BasicLayout
        HeroImage={false}
        hero="/images/about.jpg"
        title="RevoDive User Generated Content Terms of Use"
        mainclass="main"
    >
    <PageSection>
        <p>RevoGrid, LLC. (“RevoDive”) reaches out to social media users to seek their permission to feature our favorite content on our various sites, social channels, and various promotional materials. You are reading this because RevoDive has requested your permission to use your social media content in this way.</p>
        <p>If you choose to allow us to use your social media content (“User Content”) by replying with the hashtag #RevoDivePhoto, you agree to these Terms of Use.</p>
        <p>RevoDive engages a limited number of service providers to facilitate the collection and transmission to the RevoDive websites (www.RevoDive.com and others)(the “Site”), social media channels, promotional materials and other properties (“RevoDive Properties”) of User Content, including photos, text, graphics, audio, video, location information, comments and other materials from social media sites, for use by RevoDive in connection with its business, including RevoDive’s product feature, marketing, promotional, advertising and other consumer-related activities (the “RevoDive Services”).</p>
        <p>RevoDive reserves the right to alter these Terms of Use without advance notice by posting a revised Terms of Use. Accordingly, you should review the Terms of Use each time you grant permission or authorization to feature your User Content.</p>
        <h2>USER CONTENT LICENSE</h2>
        <p>You hereby grant to RevoDive and its related companies, agents, licensees, sublicensees, contractors, successors, legal representatives, assigns, and third-party service providers, and their respective retail partners, marketing or public relations agencies, and other affiliates (the “Licensed Parties”) a worldwide, perpetual, irrevocable, royalty-free, fully-paid, non-exclusive, transferable, sublicensable right to use your User Content in any manner to be determined in the Licensed Parties’ sole discretion, including but not limited to on webpages and social media pages operated by the Licensed Parties, in promotional e-mails and advertisements, and in any and all other marketing, promotional and advertising initiatives, and in any media now or hereafter known. The Licensed Parties may use, display, reproduce, distribute, transmit, create derivative works from, combine with other materials, alter and/or edit your User Content in any manner in their sole discretion, with no obligation to you whatsoever.</p>
        <p>You grant the Licensed Parties the right to use your username, real name, image, likeness, descriptions of you, location or other identifying information, including but not limited to your voice, in connection with any use of your User Content.</p>
        <p>You hereby agree and represent and warrant that (i) you are solely responsible for your User Content, (ii) you own all rights in and to your User Content and/or have obtained appropriate rights and permissions from any and all other persons and/or entities who own, manage or otherwise claim any rights with respect to such User Content, (iii) you are not a minor, (iv) the Licensed Parties’ use of your User Content as described herein will not violate the rights, including but not limited to copyright, trademark, patent, trade secret, privacy, publicity, moral, proprietary or other rights, of any third party, or any law, rule or regulation, and (v) the User Content is not libelous, defamatory, obscene, pornographic, abusive, indecent, threatening, harassing, hateful, or offensive or otherwise unlawful.</p>
        <p>You hereby release, discharge and agree to hold the Licensed Parties, and any person acting on their behalf, harmless from any liability related in any way to the Licensed Parties’ use of your User Content.</p>
        <p>The User Content that you submit is deemed non-confidential and the Licensed Parties have no obligation to maintain the confidentiality of any information, in whatever form, contained in any submission, except pursuant to the Licensed Parties’ respective privacy policies. By using this Site or the Services, you are consenting to the Licensed Parties’ collection of any personal information you provide for the Licensed Parties’ use and disclosure in connection with the use of your User Content as described herein. If you do not agree to the collection, use and disclosure of your personal information in this way, please do not use this Site or the Services or otherwise provide the Licensed Parties with personal information. Your personal information may be transferred to servers located outside the country in which you live or to third parties in other countries so that they may process personal information on the Licensed Parties behalf. By using the Site or the Services or otherwise providing the Licensed Parties with personal information, you agree to the foregoing collection, use, disclosure, transfer and processing of your information in accordance with the terms of these Terms, the Privacy Policy and applicable data protection laws and regulations.</p>
        <p>The Licensed Parties reserve the right to remove any User Content from the Site and the RevoDive Properties. If you believe any content, including User Content, residing on the Site or on the RevoDive Properties or displayed or used in connection with the RevoDive Services infringes any person’s or entity’s copyright rights, please refer to the RevoDive Copyright Policy: www.RevoDive.com/copyright-policy.</p>
        <h2>ADDITIONAL TERMS</h2>
        <p>These Terms of Use apply to the entire Site, the RevoDive Properties and RevoDive Services and to your User Content unless otherwise provided. In addition, to the extent your User Content is displayed on the Site or on any of the RevoDive Properties or in connection with the RevoDive Services, you also will be subject to additional terms of use, agreements, guidelines or rules provided by RevoDive applicable to such RevoDive Services and User Content, including but not limited to those set forth on the RevoDive website at https://www.RevoDive.com/terms, and you hereby agree to be bound by such additional terms of use or service, agreements, guidelines, instructions or rules provided or posted by RevoDive (the “RevoDive Terms”).</p>
        <p>You certify that you are at least 18 years of age.</p>
        <h2>INTELLECTUAL PROPERTY RIGHTS</h2>
        <p>The Site, RevoDive Services or RevoDive Properties may be protected by copyright, trademark and other intellectual property laws. You acknowledge and agree that you do not acquire any ownership or other rights in proprietary information and materials of RevoDive by authorizing use of your User Content or otherwise using or accessing the Site, the RevoDive Services or the RevoDive Properties.</p>
        <h2>MISCELLANEOUS</h2>
        <p>These Terms of Use are personal to you and may not be assigned or transferred by you for any reason whatsoever without RevoDive’s prior written consent; and any action or conduct in violation of the foregoing shall be void and without effect.</p>
        <p>You agree that if RevoDive does not exercise or enforce any legal right or remedy which is contained in these Terms of Use (or which RevoDive has the benefit of under any applicable law), this will not be taken to be a formal waiver of RevoDive’s rights and that those rights or remedies will still be available to RevoDive.</p>
        <p>If any court of law, having the jurisdiction to decide on this matter, rules that any provision of these Terms of Use are invalid, then that provision will be removed without affecting the rest of the Terms of Use. The remaining provisions of these Terms of Use will continue to be valid and enforceable.</p>
        <p>Last updated: January 10, 2021</p>
    </PageSection>
    </BasicLayout>
  )
}

export default UGCTerms